# Generated by Django 5.2.6 on 2025-12-01 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin especificar', max_length=200, verbose_name='Nombre del servicio')),
                ('categoria', models.CharField(choices=[('PRIORITARIO', 'Prioritario'), ('DIARIA', 'Ronda diaria'), ('SALAS', 'Servicio de salas'), ('LAB', 'Laboratorio clínico'), ('SEDES', 'Sedes externas')], default='DIARIA', max_length=20, verbose_name='Categoría')),
                ('reglas_dias', models.JSONField(blank=True, default=dict, help_text='Formato: {"lunes": true, "martes": false, ...}', verbose_name='Reglas de días')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RoundEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('prioritarios', 'Prioritarios'), ('ronda_diaria', 'Ronda diaria'), ('servicio_salas', 'Servicio de salas'), ('laboratorio_clinico', 'Laboratorio clínico'), ('sedes_externas', 'Sedes externas')], max_length=32)),
                ('subservicio', models.CharField(max_length=100)),
                ('hallazgo', models.TextField(blank=True)),
                ('placa_equipo', models.CharField(blank=True, max_length=100)),
                ('orden_trabajo', models.CharField(blank=True, max_length=100)),
                ('tiene_eventos_seguridad', models.BooleanField(default=False, verbose_name='¿Hay eventos de seguridad?')),
                ('eventos_seguridad', models.TextField(blank=True, verbose_name='Descripción de eventos de seguridad')),
                ('fuera_de_servicio', models.BooleanField(default=False, verbose_name='¿Equipo fuera de servicio?')),
                ('nombre_encargado_servicio', models.CharField(default='Sin especificar', max_length=100)),
                ('firma_servicio', models.TextField(blank=True, null=True, verbose_name='Firma del encargado del servicio')),
                ('nombre_encargado_servicio_2', models.CharField(blank=True, default='', max_length=100)),
                ('firma_servicio_2', models.TextField(blank=True, null=True, verbose_name='Firma del encargado del servicio 2')),
                ('nombre_encargado_servicio_3', models.CharField(blank=True, default='', max_length=100)),
                ('firma_servicio_3', models.TextField(blank=True, null=True, verbose_name='Firma del encargado del servicio 3')),
                ('nombre_encargado_ronda', models.CharField(default='Sin especificar', max_length=100)),
                ('firma_ronda', models.TextField(blank=True, null=True, verbose_name='Firma del encargado de la ronda')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de ronda',
                'verbose_name_plural': 'Registros de rondas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default='0', max_length=50, verbose_name='Número')),
                ('nombre', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre')),
                ('tipo_sala', models.CharField(choices=[('sala_cirugia', 'Sala de cirugía'), ('habitacion', 'Habitación'), ('consulta', 'Consulta'), ('laboratorio', 'Laboratorio'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de sala')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='rondas.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Equipo sin nombre', max_length=200, verbose_name='Nombre del equipo')),
                ('numero_placa', models.CharField(blank=True, default='', max_length=100, verbose_name='Número de placa')),
                ('estado', models.CharField(choices=[('operativo_completo', 'Operativo completo'), ('operativo_parcial', 'Operativo parcial'), ('fuera_de_servicio', 'Fuera de servicio')], default='operativo_completo', max_length=20, verbose_name='Estado')),
                ('etiquetas', models.JSONField(blank=True, default=list, help_text='Lista de etiquetas: ["crítico", "calibración", ...]', verbose_name='Etiquetas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='rondas.room', verbose_name='Sala')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='rondas.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DailySurgeryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha', models.DateField(verbose_name='Fecha del registro')),
                ('dia_semana', models.CharField(max_length=20, verbose_name='Día de la semana')),
                ('sala', models.CharField(max_length=10, verbose_name='Sala')),
                ('equipo', models.CharField(max_length=100, verbose_name='Equipo')),
                ('equipo_en_uso', models.BooleanField(default=True, verbose_name='Equipo en uso')),
                ('estado_equipo', models.CharField(blank=True, choices=[('operativo_completo', 'Operativo completo'), ('operativo_parcial', 'Operativo parcial'), ('fuera_de_servicio', 'Fuera de servicio')], max_length=20, null=True, verbose_name='Estado del equipo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('nombre_encargado_servicio', models.CharField(blank=True, max_length=100, verbose_name='Encargado del servicio')),
                ('nombre_encargado_ronda', models.CharField(blank=True, max_length=100, verbose_name='Encargado de la ronda')),
                ('firma_servicio', models.TextField(blank=True, verbose_name='Firma del encargado del servicio')),
                ('firma_ronda', models.TextField(blank=True, verbose_name='Firma del encargado de la ronda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro Diario de Cirugía',
                'verbose_name_plural': 'Registros Diarios de Cirugía',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('fecha', 'sala', 'equipo')},
            },
        ),
    ]
